# Generated by Django 4.1.3 on 2022-11-30 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Trial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="과제명")),
                ("number", models.CharField(max_length=100, verbose_name="과제번호")),
                ("period", models.CharField(max_length=100, verbose_name="연구기간")),
                ("scope", models.CharField(max_length=100, verbose_name="연구범위")),
                ("kind", models.CharField(max_length=100, verbose_name="연구종류")),
                (
                    "institution",
                    models.CharField(max_length=100, verbose_name="연구책임기관"),
                ),
                (
                    "stage",
                    models.CharField(max_length=100, verbose_name="임상시험단계(연구모형)"),
                ),
                ("target", models.IntegerField(verbose_name="전체목표연구대상자수")),
                ("department", models.CharField(max_length=100, verbose_name="진료과")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
