# Generated by Django 4.1.3 on 2022-11-30 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trials", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trial",
            name="target",
            field=models.IntegerField(null=True, verbose_name="전체목표연구대상자수"),
        ),
    ]
